CREATE TABLE "ROOT"."TB_UTIL_MEMBER" 
(	"USERID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"USERPW" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"USEREMAIL" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"PHONENUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
 CONSTRAINT "TB_UTIL_MEMBER_PK" PRIMARY KEY ("USERID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM"  ENABLE
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;
