
CREATE TABLE "ROOT"."TB_UTIL_FREEBOARD" 
(	"BNO" NUMBER NOT NULL ENABLE, 
"TITLE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"CONTENT" VARCHAR2(4000 BYTE), 
"WRITER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"COLUMN1" DATE DEFAULT sysdate, 
"COLUMN2" NUMBER DEFAULT 0, 
 CONSTRAINT "TB_UTIL_FREEBOARD_PK" PRIMARY KEY ("BNO")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM"  ENABLE
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;
