/*------------------------------------------------------------------------------
-- 개체 이름: ROOT.TB_UTIL_QUERY
-- 만든 날짜: 2021-05-28 오전 10:17:55
-- 마지막으로 수정한 날짜: 2021-05-28 오전 10:17:55
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP TABLE ROOT.TB_UTIL_QUERY CASCADE CONSTRAINTS;

CREATE TABLE ROOT.TB_UTIL_QUERY (
  SEQUENCE    NUMBER                NOT NULL, 
  USERID      VARCHAR2(20 BYTE)     NOT NULL, 
  QUERY       CLOB                  NOT NULL, 
  PARAM       CLOB                  NOT NULL, 
  TITLE       VARCHAR2(50 BYTE)     NOT NULL
)
LOB (QUERY) STORE AS (
    TABLESPACE SYSTEM
    ENABLE STORAGE IN ROW
    CHUNK 8192
    NOCACHE
    LOGGING
    STORAGE (
        INITIAL     64K
        NEXT        1M
        MINEXTENTS  1
        MAXEXTENTS  UNLIMITED
        FREELISTS    1
        FREELIST GROUPS 1
    )
)
LOB (PARAM) STORE AS (
    TABLESPACE SYSTEM
    ENABLE STORAGE IN ROW
    CHUNK 8192
    NOCACHE
    LOGGING
    STORAGE (
        INITIAL     64K
        NEXT        1M
        MINEXTENTS  1
        MAXEXTENTS  UNLIMITED
        FREELISTS    1
        FREELIST GROUPS 1
    )
)
TABLESPACE SYSTEM
PCTFREE    10
PCTUSED    40
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64K
    NEXT        1M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
    FREELISTS   1
    FREELIST GROUPS 1
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

ALTER TABLE ROOT.TB_UTIL_QUERY ADD
(
    CONSTRAINT TB_UTIL_QUERY_PK
    PRIMARY KEY ( SEQUENCE )
        USING INDEX
        TABLESPACE SYSTEM 
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64K
            NEXT 1M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            FREELISTS 1
            FREELIST GROUPS 1
        )
);

ALTER TABLE ROOT.TB_UTIL_QUERY ADD
(
    CONSTRAINT REF_KEY
    FOREIGN KEY ( USERID )
        REFERENCES ROOT.TB_UTIL_MEMBER ( USERID )
        ON DELETE  CASCADE 
);


